Repository FriendsOfTYPO3/extension_builder, pull requests merged in 2022-10, with the labels that each got.

#621 [TASK] Set the description field of backend module to textarea
  Resources/Public/jsDomainModeling/extensionProperties.js
Labels: maintenance

#624 [BUGFIX] Fix issue in JS - "Relations"
  Resources/Public/jsDomainModeling/extbaseModeling.js
Labels: bug

#622 [TASK] Add scss linter
  .github/workflows/linters.yml
  .gitignore
  Resources/Public/jsDomainModeling/extbaseModeling.css
  Resources/Public/jsDomainModeling/extbaseModeling.scss
  package-lock.json
  package.json
  sass-lint.yml
Labels: maintenance

#602 [DOCS] Update Links to the documentation
  Documentation/Index.rst
Labels: documentation

#631 [DOCS] Add changelog to documentation
  .gitattributes
  Documentation/ChangeLog/Index.rst
  Documentation/Index.rst
  docker-compose.yml
Labels: documentation
