Repository FriendsOfTYPO3/extension_builder, pull requests merged in 2023-01, with the labels that each got.

#639 [BUGFIX] resolve nullable types correctly
  Classes/Parser/Utility/NodeConverter.php
Labels: bug, tested

#643 [TASK] Fix devbox dependencies
  .devbox/composer.lock
  .gitignore
Labels: maintenance

#641 [FEATURE] add tca field description
  Classes/Domain/Model/DomainObject.php
  Classes/Domain/Model/DomainObject/AbstractProperty.php
  Classes/Service/LocalizationService.php
  Resources/Private/CodeTemplates/Extbase/Partials/TCA/PropertiesDefinition.phpt
  Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_category.php
  Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php
  Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child2.php
  Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child3.php
  Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child4.php
  Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_main.php
Labels: enhancement, tested

#640 [TASK] one controller action pair per line
  Resources/Private/CodeTemplates/Extbase/extTables.phpt
Labels: maintenance, tested
